version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
                  apt-get update && apt-get -y install gcc valgrind
      - run:
          name: Make
          command: make
      - run:
          name: test
          command: make test
      - run:
          name: Valgrind
          command: valgrind ./timer_queue_test
